### ISSUE TITLE
Command line editing?

### ISSUE THREAD

**Issue by gregfenton** [mrsarm/jshell-plugin#13]
Any thoughts or possible ways to get some form of command-line editing and/or history working with this?

I would *love* Emacs keys, but simply having the ability to up-arrow/down-arrow for history, and more importantly left-arrow/right-arrow for inline editing of the command.

**Comment by mrsarm** [comment]
Actually, you can achieve auto-completion and the ability to use up-arrow/down-arrow for history, thanks to the help of `rlwrap`, checkout this [section](https://github.com/mrsarm/jshell-plugin#tab-completion-not-working).

**Comment by gregfenton** [comment]
Brilliant!  A million thank yous!
