### ISSUE TITLE
tab completion not working

### ISSUE THREAD

**Issue by gilles-stragier** [mrsarm/jshell-plugin#2]
Hi,

When starting the gradle jshell plugin, <tabl>  seems to print a regular tab, instead of triggering code completion. If I launch jshell directly, tab works fine. 

I'm under linux, and tried to play with TERM variable a bit, but didn't succeed.

There might be something I'm missing. Could you help me, or point me to a resource to help me.

Thanks in advance

**Comment by mrsarm** [comment]
Hey, yes, I'm aware of the issue and after debugging and doing some testing I found what is the issue, but I'll need to do some refactors to solve it, hope to fix it tomorrow, if so, I'll release the RC2 with the patch and let you know

**Comment by gilles-stragier** [comment]
Thank you for your fast answer.

**Comment by mrsarm** [comment]
I'm afraid that the completion issue does not have a solution, due Gradle limitations :disappointed: : https://github.com/gradle/gradle/issues/4982

**Comment by mrsarm** [comment]
Same than #5 , cannot be fixed but yes overcome with the `rlwrap` trick explained [here](https://github.com/mrsarm/jshell-plugin#tab-completion-not-working), so closing. Checkout new version [1.1.0](https://github.com/mrsarm/jshell-plugin/releases/tag/1.1.0) released today that fixes other issues.
