### ISSUE TITLE
arrow key not work

### ISSUE THREAD

**Issue by zhjchina** [mrsarm/jshell-plugin#5]
`jshell> int a = 100`

when I type left arrow key， as follows

`jshell> int a = 100^[[D`

**Comment by mrsarm** [comment]
Yes, this is related with #2 , and unfortunately it can't be fixed because it is a issue from Gradle, not the plugin.

**Comment by turlando** [comment]
I worked around some issues using `rlwrap`. It doesn't solve all the problems, for instance the completion is broken, but at least the text navigation and the history search kind of work.

Just run: `rlwrap gradle --console plain jshell`

**Comment by mrsarm** [comment]
Wow, looks like a good trick, I'll test it later, if it work, I'll try to document it in the README file so others can use the same workaround. Thanks @turlando !

**Comment by mrsarm** [comment]
Added `rlwrap` trick in the README file that works like a charm, thanks @turlando for the trick suggestion (and please checkout the new release 1.1.0 that fixes some bugs). Closing because the issue cannot be resolved.
